language: python
python:
  - "2.7"
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
before_script:
  - curl http://qgis.org/downloads/qgis-2015.gpg.key | sudo apt-key add -
  - echo "deb http://qgis.org/debian trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install python-qgis
install:
    - pip install nose2
    - pip install pep8
    - pip install -r requirements.txt --use-mirrors
    - "./.travis/install.sh"
script:
    - nose2
    - pep8 travis_tests.py
    - "./.travis/run.sh"
