language: python
python:
  - "2.7"
env:
  - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start
virtualenv:
      system_site_packages: true
install:
    - pip install
    - pip install -r requirements.txt --use-mirrors
    - "./.travis/install.sh"
    - echo "deb http://qgis.org/debian $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list
    - echo "deb-src http://qgis.org/debian $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list
    - gpg --keyserver keyserver.ubuntu.com --recv 3FF5FFCAD71472C4
    - gpg --export --armor 3FF5FFCAD71472C4 | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get install python-qt4 -qq
    - sudo apt-get install qgis --force-yes -qq
    - sudo apt-get install python-qgis -qq
before_script:
    # Create a qgis config file and disable tips
    - qgis&
    - sleep 2 && killall -9 qgis.bin
    - sed -i -e 's/showTips\([[:digit:]]\+\)=true/showTips\1=false/' ${HOME}/.config/QGIS/QGIS2.conf
script:
    - grep  showTips ${HOME}/.config/QGIS/QGIS2.conf
    - python travis_tests/qgis_testrunner.py travis_tests.faketest
    - qgis -f travis_tests/qgis_testrunner.py travis_tests.faketest
    #- python travis_tests/qgis_testrunner.py travis_tests.test_TravisTest
