sudo: required
dist: trusty
services:
    - docker
before_install:
    - pushd .
    - cd qgis-desktop-docker && docker build -t qgis-desktop .
    - popd
install:
    - echo ${TRAVIS_BUILD_DIR}
    - docker run -d --name qgis-desktop -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 qgis-desktop
    - sleep 10
    - docker ps -a
script:
    - docker exec -it qgis-desktop sh -c "cd /tests_directory && ls -la"
    - docker exec -it qgis-desktop sh -c "cd /tests_directory && unbuffer qgis --optionspath /qgishome --nologo -f qgis-desktop-docker/qgis_testrunner.py travis_tests.test_TravisTest  2>/dev/null | grep FAILED"
    - docker exec -it qgis-desktop sh -c "cd /tests_directory && qgis --help"
    - docker exec -it qgis-desktop sh -c "cd /tests_directory && qgis_testrunner.py travis_tests.test_TravisTest"
