sudo: required
#dist: trusty
services:
    - docker
before_install:
    - pushd .
    - cd qgis-desktop-docker && docker build -t qgis-desktop .
    - popd
install:
    - echo ${TRAVIS_BUILD_DIR}
    - docker run -d --name qgis-desktop -v ${TRAVIS_BUILD_DIR}:/tests_directory -e QGIS_EXTRA_OPTIONS='--optionspath /qgishome' -e DISPLAY=:99 qgis-desktop
    - sleep 10
    - docker exec -it qgis-desktop sh -c "qgis --help 2>&1 | head -2 | grep 'QGIS - ' | perl -npe 'chomp; s/QGIS - (\d+)\.(\d+).*/\1\2/' >> /qgishome/QGIS/QGIS2.iniqgishome/QGIS/QGIS2.ini"
    - docker exec -it qgis-desktop qgis --help | head -1 | perl -npe 'chomp; s/QGIS - (\d+)\.(\d+).*/\1\2/'
    - docker ps -a
script:
    # Eureka!
    - docker exec -it qgis-desktop sh -c "qgis_testrunner.sh travis_tests.test_TravisTest"
    # Expected failure:
    - docker exec -it qgis-desktop sh -c "qgis_testrunner.sh travis_tests.test_TravisTest.run_fail"
    # Expected a python error:
    - docker exec -it qgis-desktop sh -c "qgis_testrunner.sh travis_tests.test_TravisTest.run_python_error"
