sudo: required
#dist: trusty
services:
    - docker
before_install:
    - pushd .
    - cd qgis-desktop-docker && docker build -t qgis-desktop .
    - popd

    - openssl aes-256-cbc -K $encrypted_e23aaac2ce6b_key -iv $encrypted_e23aaac2ce6b_iv -in travis_setup/id_rsa.enc -out travis_setup/id_rsa -d
    - echo travis_setup/id_rsa


install:
    - echo ${TRAVIS_BUILD_DIR}
    - docker run -d --name qgis-desktop -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 qgis-desktop
    - sleep 10
    - docker exec -it qgis-desktop sh -c "qgis_setup.sh"
    - docker ps -a
script:
    # Eureka!
    - docker exec -it qgis-desktop sh -c "qgis_testrunner.sh travis_tests.test_TravisTest"
    # Expected failure:
    - docker exec -it qgis-desktop sh -c "qgis_testrunner.sh travis_tests.test_TravisTest.run_fail"
    # Expected a python error:
    - docker exec -it qgis-desktop sh -c "qgis_testrunner.sh travis_tests.test_TravisTest.run_python_error"
